
"""Constantes de cores institucionais e semânticas para o ecossistema .assistant."""

AZUL_CAIXA = "#005CA9"
LARANJA = "#F7941D"
AZUL_CLARO = "#6CBDE1"
CINZA_ESCURO = "#333333"
VERDE = "#8DC63F"
VERMELHO = "#C4262E"
ROXO = "#7B2D8B"
TEAL = "#00A79D"
LARANJA_ESCURO = "#F15A29"
CINZA_MEDIO = "#A7A9AC"

PALETA_CATEGORICA = [
    AZUL_CAIXA,
    LARANJA,
    AZUL_CLARO,
    CINZA_ESCURO,
    VERDE,
    VERMELHO,
    ROXO,
    TEAL,
    LARANJA_ESCURO,
    CINZA_MEDIO,
]
PALETA_SEQUENCIAL = ["#E6F0FA", "#99C2E8", "#4D94D6", "#005CA9", "#003D73"]
PALETA_DIVERGENTE = [VERMELHO, LARANJA, "#FFB800", VERDE, AZUL_CAIXA]

COR_POSITIVO = VERDE
COR_NEGATIVO = VERMELHO
COR_NEUTRO = "#6C757D"
COR_ALERTA = "#FFB800"

BG_SECTION = "#F8F9FA"
BG_HEADER = "#E8F4FD"
TEXTO_PRINCIPAL = "#1A1A1A"
TEXTO_SECUNDARIO = "#6C757D"
BORDA_CAIXA = AZUL_CAIXA
