from pathlib import Path
ROOT=Path(__file__).resolve().parents[4]
P=ROOT/'ambiente_fonte/.assistant/hub_prompts'
N=['auditoria_skills','comentar_notebook','novo_projeto','tutor_explicar']
D={
'auditoria_skills':('auditar uma skill ou o output produzido por ela','briefing para auditar implementação de Agent Skill ou artefato contra o contrato produtor','separar descobribilidade, estrutura, segurança, execução e aderência','skill/output e pedido original podem ser anexados conforme o modo','a auditoria seria feita de memória ou correção foi autorizada sem diagnóstico','modo, skill alvo, output/pedido quando aplicáveis, casos de uso, prompts de teste e dependências','Um Markdown bem formado pode apontar para recurso inexistente ou rotear mal. Auditoria exige evidência além de abrir o arquivo.','Escolha IMPLEMENTAÇÃO ou OUTPUT, fixe o contrato e percorra frontmatter, recursos, segurança e testes antes do veredito.','Modo, contrato produtor, escopo user/workspace, dependências, severidade e autorização para corrigir.','Confundir palavra-chave com descobribilidade, editar description sem reteste ou aprovar script não executado.','Para explicar uma skill use `tutor_explicar`; para documentação use `comentar_notebook`.','Monte matriz requisito→evidência, valide caminhos/scripts e registre o que não foi executado.','O exemplo apenas lê um `SKILL.md`; não cria tabela.'),
'comentar_notebook':('documentar notebook sem alterar lógica por acidente','briefing para revisar, editar documentação ou criar narrativa de notebook','calibrar documentação ao público e preservar comportamento quando exigido','notebook/células alvo e público estão definidos','o notebook ainda muda muito ou documentação é usada como refatoração implícita','notebook/células, modo, público, profundidade, objetivo, convenções e restrições','Comentários podem ficar obsoletos ou mascarar código pouco claro. O formulário separa revisão, edição e documentação.','Mapeie entradas, saídas e efeitos; depois altere somente a camada documental permitida e liste o que foi preservado.','REVISÃO/EDIÇÃO/DOCUMENTAÇÃO, público, profundidade, partes imutáveis e PII.','Refatorar sem autorização, repetir literalmente o código ou afirmar reexecução inexistente.','Para aprender código use `tutor_explicar`; para auditar output use `auditoria_skills`.','Compare código e ordem de células, confira referências e separe comentário factual de recomendação.','O exemplo apenas lê `exemplo_pit_join.py`; o estado atual já exige saída colada nos notebooks de exemplo.'),
'novo_projeto':('iniciar projeto analítico com contexto reutilizável','briefing para charter, árvore de projeto, contexto local e backlog antes de criar recursos','evitar arquitetura prematura e tornar objetivo, owners, métricas e ambientes verificáveis','há problema/decisão e stakeholders a organizar','é usado como substituto da descoberta com negócio ou sem owner/prazo','nome, objetivo, donos, métricas, fontes, entidade/target, entregáveis, ambientes, repo e modo','Projetos começam mal quando solução é escolhida antes de problema, governança e definition of done.','Defina charter e limites, proponha estrutura simples e use `AGENTS.md` apenas no diretório correto; separe plano de criação/deploy.','Objetivo mensurável, owner/aprovador, guardrails, diretório ancestral, ambientes e modo.','Duplicar instruções globais, incluir segredos, criar recursos cedo ou confundir convenção local com recurso oficial.','Para pipeline definido use `pipeline`; para baseline use `baseline_orchestration`.','Confirme local do `AGENTS.md`, ausência de segredos/placeholders e aceite de cada entregável.','O exemplo cria `workspace.default.hub_exemplo_clientes` só como contexto sintético; o modo pedido é somente plano.'),
'tutor_explicar':('explicar código e conceitos no nível certo','briefing de tutoria para código, tabela, erro ou pipeline anexado','adaptar profundidade e vocabulário ao nível e objetivo prático','o objeto real está anexado e a dúvida é concreta','é usado como revisão de código ou fonte única para comportamento de plataforma','objeto/pergunta, nível, profundidade, objetivo, ambiente, contexto e restrições','Explicação genérica pode estar correta e ainda não ensinar. O formulário ancora a resposta no objeto e na tarefa futura.','Comece com mapa mental, defina termos e avance ao detalhe; diferencie comportamento documentado, prática e opinião.','Nível, granularidade, ambiente/versão, objetivo prático e permissão para experimento.','Explicar código não lido, usar API obsoleta ou confundir tutoria com revisão.','Para editar documentação use `comentar_notebook`; para avaliar correção use auditoria/revisão.','Cheque se exemplos usam o objeto real, termos estão definidos e claims de plataforma têm versão/referência.','O exemplo é somente leitura de `pit_join.py`; nenhuma tabela é criada.')}

def render(n,d):
 t,w,p,u,a,need,prob,intu,dec,risk,alt,val,extra=d; nb=f'exemplo_{n}.py'
 return f'''# `{n}` — {t}\n\n<!-- readme-objeto: 1.0.0 -->\n\n{w.capitalize()}. O prompt organiza o pedido, mas não executa a tarefa sozinho.\n\n## Visão rápida\n\n| Pergunta | Resposta |\n|---|---|\n| O que é? | {w.capitalize()}. |\n| Para que serve? | {p.capitalize()}. |\n| Use quando... | {u.capitalize()}. |\n| Evite quando... | {a.capitalize()}. |\n| Precisa de... | {need.capitalize()}. |\n| Entrega... | Briefing estruturado; evidências dependem da interação real. |\n\nComece pelo [briefing original]({n}.md) e leia o [notebook de exemplo]({nb}).\n\n## 1. O que é?\n\n{w.capitalize()}. O arquivo `{n}.md` é a fonte do formulário e do contrato de saída.\n\n## 2. Que problema este recurso resolve?\n\n{prob}\n\n## 3. Quando faz sentido usar?\n\nUse quando {u}. {p.capitalize()}.\n\n## 4. Quando não usar?\n\nEvite quando {a}. Gerar texto ou código não valida premissas ausentes.\n\n## 5. Como funciona, intuitivamente?\n\n{intu}\n\n## 6. Exemplo de situação\n\nPreencha o briefing com um caso real equivalente ao cenário demonstrado no notebook, mantendo recursos, público e objetivo explícitos.\n\n## 7. O que você precisa antes de usar?\n\nTenha {need}. Use `NÃO INFORMADO` para lacunas em vez de inventar defaults.\n\n## 8. O que este recurso entrega?\n\nEntrega um pedido estruturado. O contrato do briefing lista os artefatos esperados; confira separadamente o que foi proposto, executado ou validado.\n\n## 9. Como usar este recurso no Hub?\n\nAbra [{n}.md]({n}.md), preencha os campos e selecione recursos reais. O [notebook]({nb}) demonstra o preenchimento. {extra}\n\n## 10. Decisões e configurações que mais importam\n\n{dec}\n\n## 11. Limitações, riscos e armadilhas\n\n{risk} A instrução textual não substitui permissões, revisão nem controles técnicos.\n\n## 12. Quais são as alternativas?\n\n{alt}\n\n## 13. Como saber se o resultado faz sentido?\n\n{val} Separe fatos observados, hipóteses e recomendações.\n\n## 14. Arquivos relacionados e próximos passos\n\nO [briefing]({n}.md), o [notebook]({nb}) e o [catálogo](../README.md) formam o caminho local. O próximo passo depende do diagnóstico, não do simples término da resposta.\n\n## 15. Referências\n\nA descrição foi confrontada com [{n}.md]({n}.md) e [{nb}]({nb}) na base R11. Para comportamento atual de Genie Code, Agent Skills e instruções, consulte a documentação oficial do Databricks antes de operar em produção.\n'''

def write(p,t): p.parent.mkdir(parents=True,exist_ok=True); p.write_text(t,encoding='utf-8')
def rep(p,o,n):
 s=p.read_text(encoding='utf-8')
 if n in s:return
 if s.count(o)!=1:raise RuntimeError((p,o[:60],s.count(o)))
 write(p,s.replace(o,n,1))
for n,d in D.items(): write(P/n/'README.md',render(n,d))
for n in N:
 p=P/n/f'exemplo_{n}.py'; s=p.read_text(encoding='utf-8'); b='# MAGIC 📘 Guia local: [`README.md`](./README.md)'
 if b not in s:
  title=f'# MAGIC # `{n}`'; pos=s.index(title); end=s.index('\n',pos); write(p,s[:end+1]+'# MAGIC\n'+b+'\n'+s[end+1:])
aud=P/'auditoria_skills/exemplo_auditoria_skills.py'
rep(aud,'**Como ler.** A skill escolhida é a mais nova, e é a que menos histórico tem. É de propósito: auditar a skill que já passou por revisão humana mede pouco. E há um detalhe honesto — ela é a única cuja `description` ainda não passou por forward test.','**Como ler.** O alvo é uma skill real publicada. Audite o estado atual do arquivo e dos testes, sem assumir que histórico de revisão ou palavras-chave substituem evidência de roteamento.')
rep(aud,'1. Rode a Parte 1 deste notebook — ela cria `nenhuma — o insumo é uma pasta de skill`.','1. Rode a Parte 1 deste notebook — ela não cria tabela; apenas lê o `SKILL.md` selecionado.')
com=P/'comentar_notebook/exemplo_comentar_notebook.py'
rep(com,'**Como ler.** O alvo é um notebook que já existe e que você pode abrir ao lado. Escolhi o `exemplo_pit_join` de propósito: ele é um dos onze sem saída colada, então tem espaço real para melhorar — e você consegue conferir se a sugestão do assistente faz sentido.','**Como ler.** O alvo é um notebook real que você pode abrir ao lado. O estado atual do repositório já exige saída colada nos exemplos; o exercício aqui avalia clareza documental, não uma dívida antiga de outputs.')
rep(com,'1. Rode a Parte 1 deste notebook — ela cria `nenhuma — o insumo é um notebook`.','1. Rode a Parte 1 deste notebook — ela não cria tabela; apenas lê o notebook selecionado.')
tut=P/'tutor_explicar/exemplo_tutor_explicar.py'
rep(tut,'- Ambiente/compute/runtime: Databricks Free, serverless, Spark 4.1','- Ambiente/compute/runtime: Databricks Free, serverless; confirme a versão efetiva do Spark antes de depender de comportamento específico')
rep(tut,'1. Rode a Parte 1 deste notebook — ela cria `nenhuma — o insumo é um trecho de código`.','1. Rode a Parte 1 deste notebook — ela não cria tabela; apenas lê o módulo Python selecionado.')
