from pathlib import Path
ROOT=Path(__file__).resolve().parents[4]
P=ROOT/'ambiente_fonte/.assistant/hub_prompts'
N=['baseline_orchestration','explainability','monitoramento_modelo','pipeline','safra']
D={
'baseline_orchestration':('estabelecer um baseline honesto antes de otimizar','briefing para estruturar baseline de ML','criar referência simples antes de tuning','target, cutoff e split já definidos','target ou ponto no tempo ainda ambíguos','dataset, unidade/chave, target, cutoff, horizonte, split e métrica','Sem uma referência simples, complexidade pode parecer ganho. O formulário força framing, validação temporal e custo do erro antes do treino.','Declare o instante da decisão e o que podia ser usado; compare baseline ingênuo e baseline de modelo com split coerente.','Cutoff, horizonte, split, evento positivo, colunas proibidas e métrica.','Leakage entre splits, preprocessing fora do treino e holdout reutilizado.','Use `eda_completa` antes dos dados estarem compreendidos; use `feature_engineering` antes do treino quando faltarem atributos.','Reconfira sobreposição entre splits, prevalência e ao menos uma métrica contra a referência ingênua.','O exemplo sobrescreve `workspace.default.hub_exemplo_clientes`.'),
'explainability':('explicar previsões sem transformar contribuição em causalidade','briefing para explicabilidade global/local de modelo','alinhar modelo, população, método e público','modelo e split podem ser identificados','versão do modelo ou população não estão confirmadas','modelo/run, dataset/split, target, objetivo, público, método e amostra','Explicações são fáceis de superinterpretar. O formulário separa performance, contribuição do modelo, associação e efeito causal.','Fixe modelo e população, escolha a pergunta explicativa e o método, então aplique sanity checks.','Versão do modelo, split, espaço da saída, explainer/background, amostra e público.','Explicar versão errada, tratar SHAP como efeito causal ou expor PII.','Para performance use baseline/monitoramento; para hipótese estatística use `stat_check`.','Confirme modelo, schema, split, classes, sinal e estabilidade quando aplicável.','O exemplo sobrescreve `workspace.default.hub_exemplo_clientes`; SHAP é dependência opcional.'),
'monitoramento_modelo':('monitorar modelo sem transformar variação em incidente','briefing para monitoramento técnico, de dados, drift e performance','ligar baseline, janela, atraso do rótulo, direção das métricas e owners','modelo, referência e janelas podem ser identificados','rótulo ainda não maturou ou limite foi copiado sem calibração','modelo, caminho de inferência, baseline, janela, label delay, métricas, segmentos e owners','Drift, qualidade de dados, falha operacional e queda de performance são fenômenos diferentes. Misturá-los cria alarmes sem ação.','Separe saúde operacional, dados, drift, performance e negócio; alinhe predição e rótulo antes do alerta.','Baseline, label delay, direção/unidade, janela, mínimo N, limite e owner.','Performance sobre rótulo imaturo, `abs(delta)` e retreino por um único ponto.','Para qualidade use `data_quality`; para performance inicial use baseline.','Teste melhora, piora, baixo volume, nulos e ausência de rótulo; confira denominadores.','O código do exemplo sobrescreve `hub_exemplo_monitor_ref` e `hub_exemplo_monitor_atual`; a prosa antiga citava outro nome.'),
'pipeline':('desenhar pipeline operável antes de fazer deploy','briefing para pipeline de dados com Lakeflow quando apropriado','explicitar fontes, destino, modo, chaves, schema, qualidade, SLO e ambientes','contratos e reprocessamento podem ser descritos','origem ainda está incorreta ou ambiente alvo indefinido','objetivo, fontes, destinos, modo, chaves, schema, regras, SLO e ambientes','Automatizar transformação sem idempotência, schema e recuperação apenas repete erros com maior frequência.','Comece pelos contratos e chegada; desenhe estado, deduplicação, late data e qualidade antes de bundle/deploy.','Batch/streaming/CDC, chave/sequência, schema, expectations, checkpoint, ambientes e rollback.','Streaming sem necessidade, deploy no catálogo errado e reprocessamento não idempotente.','Para qualidade use `data_quality`; para organizar projeto novo use `novo_projeto`.','Teste duplicata, atraso, reprocessamento, schema novo, falha parcial e parametrização por ambiente.','O exemplo sobrescreve `workspace.default.hub_exemplo_clientes`; ele não cria pipeline real.'),
'safra':('comparar safras na mesma maturidade','briefing para safra/vintage com coorte, idade, numerador, denominador e censura','evitar comparar coortes com maturidade diferente','coorte, maturidade e evento estão claros','célula imatura é tratada como zero ou regra normativa não tem fonte','dataset, entidade/chave, safra, idade, evento, denominador, métrica e censura','Safras recentes parecem melhores quando tiveram menos tempo para maturar. Sem denominador e censura a curva pode enganar.','Crie grade safra×idade, preserve células não observáveis e compare idades equivalentes.','Entrada na coorte, MOB, evento cumulativo, denominador, censura e maturidade comum.','Somar taxas cumulativas, dupla contagem e atribuir causa a mix/maturação.','Use `vintage_analysis` para cálculo reutilizável; survival para censura mais formal.','Reconcilie entidades, numerador, denominador, células imaturas e maturidade comum.','O exemplo sobrescreve `workspace.default.hub_exemplo_safras`; base sintética não cria regra regulatória.')}

def render(n,d):
 t,w,p,u,a,need,prob,intu,dec,risk,alt,val,extra=d; nb=f'exemplo_{n}.py'
 return f'''# `{n}` — {t}\n\n<!-- readme-objeto: 1.0.0 -->\n\n{w.capitalize()}. O prompt organiza o pedido, mas não executa a tarefa sozinho.\n\n## Visão rápida\n\n| Pergunta | Resposta |\n|---|---|\n| O que é? | {w.capitalize()}. |\n| Para que serve? | {p.capitalize()}. |\n| Use quando... | {u.capitalize()}. |\n| Evite quando... | {a.capitalize()}. |\n| Precisa de... | {need.capitalize()}. |\n| Entrega... | Briefing estruturado; evidências dependem da interação real. |\n\nComece pelo [briefing original]({n}.md) e leia o [notebook de exemplo]({nb}).\n\n## 1. O que é?\n\n{w.capitalize()}. O arquivo `{n}.md` é a fonte do formulário e do contrato de saída.\n\n## 2. Que problema este recurso resolve?\n\n{prob}\n\n## 3. Quando faz sentido usar?\n\nUse quando {u}. {p.capitalize()}.\n\n## 4. Quando não usar?\n\nEvite quando {a}. Gerar texto ou código não valida premissas ausentes.\n\n## 5. Como funciona, intuitivamente?\n\n{intu}\n\n## 6. Exemplo de situação\n\nPreencha o briefing com um caso real equivalente ao cenário demonstrado no notebook, mantendo recursos, período e unidade de análise explícitos.\n\n## 7. O que você precisa antes de usar?\n\nTenha {need}. Use `NÃO INFORMADO` para lacunas em vez de inventar defaults.\n\n## 8. O que este recurso entrega?\n\nEntrega um pedido estruturado. O contrato do briefing lista os artefatos esperados; confira separadamente o que foi apenas proposto, executado ou validado.\n\n## 9. Como usar este recurso no Hub?\n\nAbra [{n}.md]({n}.md), preencha os campos e selecione recursos reais. O [notebook]({nb}) demonstra o preenchimento. {extra}\n\n## 10. Decisões e configurações que mais importam\n\n{dec}\n\n## 11. Limitações, riscos e armadilhas\n\n{risk} A instrução textual não substitui permissões, revisão nem controles técnicos.\n\n## 12. Quais são as alternativas?\n\n{alt}\n\n## 13. Como saber se o resultado faz sentido?\n\n{val} Separe fatos observados, hipóteses e recomendações.\n\n## 14. Arquivos relacionados e próximos passos\n\nO [briefing]({n}.md), o [notebook]({nb}) e o [catálogo](../README.md) formam o caminho local. O próximo passo depende do diagnóstico, não do simples término da resposta.\n\n## 15. Referências\n\nA descrição foi confrontada com [{n}.md]({n}.md) e [{nb}]({nb}) na base R11. Para comportamento de plataforma, consulte a documentação oficial atual do Databricks antes de operar em produção.\n'''

def write(p,t): p.parent.mkdir(parents=True,exist_ok=True); p.write_text(t,encoding='utf-8')
def rep(p,o,n):
 s=p.read_text(encoding='utf-8')
 if n in s:return
 if s.count(o)!=1:raise RuntimeError((p,o[:60],s.count(o)))
 write(p,s.replace(o,n,1))
for n,d in D.items(): write(P/n/'README.md',render(n,d))
for n in N:
 p=P/n/f'exemplo_{n}.py'; s=p.read_text(encoding='utf-8'); b='# MAGIC 📘 Guia local: [`README.md`](./README.md)'
 if b not in s:
  title=f'# MAGIC # `{n}`'; pos=s.index(title); end=s.index('\n',pos); write(p,s[:end+1]+'# MAGIC\n'+b+'\n'+s[end+1:])
mon=P/'monitoramento_modelo/exemplo_monitoramento_modelo.py'
rep(mon,'| Escrita | **sim** — cria a tabela `workspace.default.hub_exemplo_clientes` para o chat poder consultá-la |','| Escrita | **sim** — cria/sobrescreve `workspace.default.hub_exemplo_monitor_ref` e `workspace.default.hub_exemplo_monitor_atual` para o chat consultá-las |')
rep(mon,'1. Rode a Parte 1 deste notebook — ela cria `workspace.default.hub_exemplo_clientes`.','1. Rode a Parte 1 deste notebook — ela cria/sobrescreve `workspace.default.hub_exemplo_monitor_ref` e `workspace.default.hub_exemplo_monitor_atual`.')
