"""Edições R09 estritamente editoriais e integração mínima de agregadores."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[4]
ASSISTANT=ROOT/'ambiente_fonte/.assistant'
EDITS={
'curves_plotly':[
("# MAGIC **O que este helper faz.** Gera ROC, precisão-recall, lift e KS com o mesmo tema, sobre amostra limitada.\n","# MAGIC **O que este helper faz.** Gera ROC, precisão-recall, lift e KS com o mesmo tema sobre vetores já disponíveis no driver. O parâmetro `n` só altera o N exibido no rodapé; **não subamostra** os dados.\n# MAGIC\n# MAGIC **Guia local completo:** [README deste objeto](README.md).\n"),
("# MAGIC É por isso que ROC quase nunca fica feia em base desbalanceada.\n","# MAGIC Por isso, em base desbalanceada, leia ROC junto com PR, lift, prevalência e capacidade operacional; uma AUC alta não garante precisão adequada no recorte acionável.\n"),
("# MAGIC - **Sobre a base inteira.** As funções aceitam `n` porque plotar milhões de pontos no driver não termina.\n","# MAGIC - **Sobre milhões de linhas esperando que `n` limite o custo.** `n` é somente metadado visual; amostre ou agregue antes de trazer vetores grandes ao driver.\n")],
'drift_detection':[
("# MAGIC **O que este helper faz.** Calcula os três, e varre várias features de uma vez separando numéricas de categóricas.\n","# MAGIC **O que este helper faz.** Calcula os três, e varre várias features de uma vez separando numéricas de categóricas. Sem thresholds do consumidor, mede evidência e retorna `NOT_CLASSIFIED`.\n# MAGIC\n# MAGIC **Guia local completo:** [README deste objeto](README.md).\n"),
("# MAGIC referência e são escolha de quem calcula; em categórica as \"faixas\" já\n# MAGIC existem, e o índice fica estável.\n","# MAGIC referência e são escolha de quem calcula; em categórica as \"faixas\" já\n# MAGIC existem. Isso evita escolher bins numéricos, mas categorias raras, novas ou de alta cardinalidade continuam exigindo revisão.\n"),
("# MAGIC ## Quando **não** usar\n","# MAGIC **Nota de contrato:** no ramo categórico atual, `min_non_null` é comparado ao comprimento total da série, apesar do nome do parâmetro. Se houver muitas ausências, valide externamente a contagem não nula.\n# MAGIC\n# MAGIC ## Quando **não** usar\n")],
'metrics_report':[
("# MAGIC # `metrics_report` — métricas que não mentem em base desbalanceada\n","# MAGIC # `metrics_report` — métricas sob população e threshold declarados\n"),
("# MAGIC **O que este helper faz.** Devolve o conjunto de métricas de classificação com o limiar **declarado**, e as de regressão quando o caso é outro.\n","# MAGIC **O que este helper faz.** Devolve métricas binárias e de regressão. As métricas hard usam o threshold declarado; `ks_pct` está na escala 0–100.\n# MAGIC\n# MAGIC **Guia local completo:** [README deste objeto](README.md).\n"),
("# MAGIC O par que decide é **precisão e recall**, e eles se movem em direções\n# MAGIC opostas conforme o limiar. AUC resume a ordenação — o quanto o score separa\n# MAGIC — e é independente do limiar, por isso é a métrica que sobrevive quando a\n# MAGIC política de corte muda.\n","# MAGIC Precisão e recall descrevem consequências diferentes do corte e mudam com o threshold. AUC resume ordenação, mas não escolhe política operacional nem substitui calibração, custo ou capacidade.\n"),
("# MAGIC O erro de interpretação mais provável: comparar o f1 de dois modelos\n# MAGIC medidos com limiares diferentes. A comparação justa é pela AUC, ou pelo\n# MAGIC mesmo limiar nos dois.\n","# MAGIC Para comparar F1, precisão e recall, mantenha a mesma regra de corte e população; para AUC/AP e outras métricas sem corte, mantenha população, target e protocolo de avaliação comparáveis.\n")],
'mlflow_run':[
("# MAGIC **O que este helper faz.** Abre um run isolado e **recusa fechá-lo** sem dataset, split, assinatura e limitações declaradas.\n","# MAGIC **O que este helper faz.** Abre um run isolado e **recusa fechá-lo** sem o conjunto mínimo de registro. O efeito depende do tracking MLflow disponível no ambiente.\n# MAGIC\n# MAGIC **Guia local completo:** [README deste objeto](README.md).\n"),
("# MAGIC | Compute | serverless ou clássico, indiferente |\n","# MAGIC | Compute | runtime com tracking MLflow funcional; revalidar no destino |\n"),
("# MAGIC | Diferença Free × trabalho | **sim** — nenhum run do MLflow abre no serverless do Free; ver a seção 3 |\n","# MAGIC | Diferença Free × trabalho | a seção 3 preserva observação histórica datada; não é regra universal do Free nem garantia sobre compute clássico |\n"),
("# MAGIC ## 3. O registro completo — e por que ele não abre aqui\n","# MAGIC ## 3. O registro completo — e a observação histórica deste runtime\n"),
("# MAGIC então o notebook continua sendo executável e se auto-verifica — em compute\n# MAGIC clássico, no trabalho, ela imprime `run completo aceito e fechado`.\n","# MAGIC então o notebook continua sendo executável e se auto-verifica. Em outro runtime, inclusive clássico, execute novamente: o sucesso depende do tracking/configuração vigentes.\n")],
'performance_monitor':[
("# MAGIC **O que este helper faz.** Registra métricas ao longo do tempo e as compara contra limites **calibrados e declarados**, devolvendo o veredito.\n","# MAGIC **O que este helper faz.** Registra métricas ao longo do tempo e compara deterioração contra uma política declarada, devolvendo status e candidato a investigação — nunca autorização automática de retreino.\n# MAGIC\n# MAGIC **Guia local completo:** [README deste objeto](README.md).\n"),
("# MAGIC Variação mês a mês é ruído; o que decide retreino é a comparação contra o\n# MAGIC limite, e a persistência abaixo dele.\n","# MAGIC Variação mês a mês pode ser ruído; política e persistência ajudam a disparar **investigação**. Retreino exige causa raiz, avaliação offline e governança.\n"),
("# MAGIC ### Contrato atualizado em 09/09/2026\n","# MAGIC **Leia `should_retrain()` pelo conteúdo do retorno:** o nome é legado e `automatic_retrain_authorized` permanece `False`.\n# MAGIC\n# MAGIC ### Contrato atualizado em 09/09/2026\n")]
}
CAT_OLD="Métrica interna, ranking, embedding e SHAP são evidências diferentes. Nenhum desses objetos cria causalidade, persona, política ou homologação por conta própria.\n\n#### 📊 Risco de Crédito e Scorecards\n"
CAT_NEW="Métrica interna, ranking, embedding e SHAP são evidências diferentes. Nenhum desses objetos cria causalidade, persona, política ou homologação por conta própria.\n\n#### 📘 Guias locais R09 — avaliação, drift e MLOps\n\n- [Curvas ROC/PR/lift/KS](ml/curves_plotly/README.md) — `n` é metadado visual e não subamostra;\n- [Drift de features](ml/drift_detection/README.md) — PSI, KS, CSI e política explícita;\n- [Relatório de métricas](ml/metrics_report/README.md) — `ks_pct` em 0–100;\n- [Run MLflow governado](ml/mlflow_run/README.md) — efeito externo e runtime a revalidar;\n- [Monitor de performance](ml/performance_monitor/README.md) — investigação, sem retreino automático.\n\n#### 📊 Risco de Crédito e Scorecards\n"
INDEX_OLD="O contrato vigente é **1.0.0**. A R07 foi aceita e integrada pelo PR nº 25 no commit `b73bbb9`, após reconciliação com a V04 e seu checkpoint documental. A R08 documenta `autoencoder_anomaly`, `cluster_profiling`, `clustering_suite`, `explainability_report`, `shap_explainer` e `umap_viz` sem alterar suas implementações/fachadas. A cobertura esperada é **55/75 operacionais e 3/3 exemplares, com 20 pendências**; somente a saída do validador da árvore fechada é fonte de verdade. Isso não significa publicação no workspace nem aceite antecipado dos seis textos.\n\nConsulte o [relatório R08](RELATORIO_R08.md), a [matriz nominal](MATRIZ_ALTERACOES_R08.md) e os [achados](ACHADOS_R08.md). A próxima parada é a revisão desta leva antes da R09.\n"
INDEX_NEW="O contrato vigente é **1.0.0**. A R08 foi aceita e integrada pelo PR nº 27 no commit `d5945e0`. A R09 documenta `curves_plotly`, `drift_detection`, `metrics_report`, `mlflow_run` e `performance_monitor`, preservando implementações/fachadas. A cobertura candidata é **60/75 operacionais e 3/3 exemplares, com 15 pendências**; o validador da árvore fechada é fonte de verdade.\n\nConsulte o [relatório R09](RELATORIO_R09.md), a [matriz nominal](MATRIZ_ALTERACOES_R09.md), os [achados](ACHADOS_R09.md) e o [registro de recuperação](RECUPERACAO_R09.md). A próxima parada é freeze técnico e revisão antes da R10.\n"
def rep(path,old,new):
 t=path.read_text(encoding='utf-8'); assert t.count(old)==1,(path,t.count(old)); path.write_text(t.replace(old,new),encoding='utf-8')
def apply():
 for obj,edits in EDITS.items():
  p=ASSISTANT/f'hub_snippets/ml/{obj}/exemplo_{obj}.py'
  for old,new in edits: rep(p,old,new)
 rep(ASSISTANT/'hub_snippets/README.md',CAT_OLD,CAT_NEW)
 rep(ROOT/'docs/sprints/readmes_objetos/README.md',INDEX_OLD,INDEX_NEW)
if __name__=='__main__': apply()
